apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
  namespace: argocd
type: Opaque
stringData:
  registries.conf: |
    registries:
    - name: local-registry
      api_url: http://95.217.144.59:5000
      prefix: 95.217.144.59:5000
      insecure: true
      ping: yes
      credentials: secret:argocd/local-registry-secret
